assignees = "RishiDarkDevil"
authors = ""
bump_mode = "pr"
collection_description = ""
conduct_contact = ""
crate = ""
description = ""
license = "MIT OR Apache-2.0"
line_width = "100"
logo = ""
name = ""
repository = "atomix-labs/atxp"
runner_labels = ""
