version = 2

[[profiles]]
name = "editorconfig"
digest = "6d23b97fe90d15285da1303dbd557180c228d08683b32dd9c24cc640f934e643"

[profiles.source]
path = "profiles"

[[profiles]]
name = "git-attributes"
digest = "05247d11207937c45bb7d470447091d9a5ace15a4fa11f741adc4d3239bf040b"

[profiles.source]
path = "profiles"

[[profiles]]
name = "git-ignore"
digest = "1bac58298a73473cc579082a13716ca67166f0b34a32af8ff5a269919a9fa11e"

[profiles.source]
path = "profiles"

[[profiles]]
name = "mise"
digest = "e70cc8a848a4765bcc16f065512d09037892803a0280bd22d2036b9a587c297c"

[profiles.source]
path = "profiles"

[[profiles]]
name = "just"
digest = "ea4986f8c81d94e4da7bdddf5979216a45f018566fa095cbd1e7d8cc70948716"

[profiles.source]
path = "profiles"

[[profiles]]
name = "setup"
digest = "f17b30b202e9032f1705e4a6fe470007458222af145bb604e3fccec7c77a82ed"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-automation"
digest = "3e97f13d0936e32f4bb9d0eebbec77a385c497936d9792ffd02c5ae6cc27196b"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-ci"
digest = "175aee271d28032df505e88ed28a1ceebac0ae23d368b2ad5ed0a5f4cfc486a7"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]
pages = ["target"]

[[profiles]]
name = "github-watch"
digest = "375b7154e253cfc2787688f4532b3d7ae25fb36950cc9739747fcf9d3fe35754"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-bump"
digest = "866fb4b557a43bf7f8614f3ed526084ed0de865fa50de75ee9f6dea54f497f30"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-dependabot"
digest = "181f496f824f308cb5b78cb70aa0188cb45d517fdf481d2b9c8087990dbf6c10"

[profiles.source]
path = "profiles"

[[profiles]]
name = "git-commits"
digest = "ec967b5e8de40481772a61fde847a7d20b476c0ee04b1599c1c4974eb6d65226"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]

[[profiles]]
name = "git-changelog"
digest = "172c88a38976c37963d984460ab8b9000521bdbc4e6c65d7755e2677c51a7ea1"

[profiles.source]
path = "profiles"

[profiles.features]
breaking-changes = ["target"]

[[profiles]]
name = "spelling"
digest = "ad9426f64441ff104a1b58c3643235928205a1043e2ad267901165c74512cf36"

[profiles.source]
path = "profiles"

[[profiles]]
name = "toml"
digest = "1268b149e644238b0695b38af3ab21cef2bf488a7a25ec41adac8a0cc61d0eaa"

[profiles.source]
path = "profiles"

[profiles.features]
format = ["default"]
lint = ["default"]
schemas = ["devset-collection/schemas"]

[[profiles]]
name = "dprint"
digest = "30476c106433d5344d53f33288efa172f2faa8fa403d87ef715b31d6fd98831b"

[profiles.source]
path = "profiles"

[[profiles]]
name = "markdown"
digest = "5aea4ad9a12a85642a751748574734549c88a52da302e0e79c25e3b1fc331df8"

[profiles.source]
path = "profiles"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "python"
digest = "b970d5da2458ceb289b559e052621784f1741a59c4e89be5facd7a6a13473e1d"

[profiles.source]
path = "profiles"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "yaml"
digest = "7381512e47aec02a545965d326936106253dd9021349b5fdf3511a78f1678130"

[profiles.source]
path = "profiles"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "shell"
digest = "4f9176fc3685086a3e6024b683269ecfabe409f0963e7a8437f1052594676035"

[profiles.source]
path = "profiles"

[profiles.features]
lint = ["default"]

[[profiles]]
name = "github-workflow-lint"
digest = "06500b149d81516f0deb56d03183e393b5e195e4b6c9b4986f1b26026d8460d0"

[profiles.source]
path = "profiles"

[profiles.features]
actionlint = ["default"]
policies = ["default"]
zizmor = ["default"]

[[profiles]]
name = "suppressions"
digest = "9c47b0af3c3249e7cc43c73bd091892b5bd88a3dd68d79dae11522dbe0b89133"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-release"
digest = "075827710e4fa45e5ce0e7ff15265a80fce3363b7f31a0baf46f76278824a256"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]

[[profiles]]
name = "devset"
digest = "c043986a9a65b08708b4dc1224620234f5f0ceb8d00e23a18692d85e892bde25"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]

[[profiles]]
name = "devset-collection"
digest = "29baecb94eaa14e6342967a7ebd8a33b5210832c35da2ab670ae61aa9e0758fd"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]
pins = ["target"]
schemas = ["default"]

[[profiles]]
name = "agents"
digest = "2b328e3c384b3763ea61103a50887537e38ff4a748b4ebc636cb4a342216d58b"

[profiles.source]
path = "profiles"

[profiles.features]
hook = ["default"]
