version = 2

[[profiles]]
name = "editorconfig"
digest = "e1b9c57689290be868ff3a1d81e40985cbdaff418a0ac7f638d3d9b63132298a"

[profiles.source]
path = "profiles"

[[profiles]]
name = "git-attributes"
digest = "1f0e46fc40b06a0acb7518bf5cbbaa084b035cf1cbc5fd969dc29897806087ab"

[profiles.source]
path = "profiles"

[[profiles]]
name = "git-ignore"
digest = "1fd8a8c36ef5530a189d137ec7487162280e10cc8b3aa667624a519750788425"

[profiles.source]
path = "profiles"

[[profiles]]
name = "mise"
digest = "5c5fcbf2b3aea4b3fdc3199248c35653a90b79c735ea9d71c4e6f4e22b868615"

[profiles.source]
path = "profiles"

[[profiles]]
name = "just"
digest = "7b3687051e2c7037f0a19201d20e343d995e51114cc5bea4843fa34fd762f703"

[profiles.source]
path = "profiles"

[[profiles]]
name = "setup"
digest = "8a99988f35c605d7338cd8a6b480922dd14d0ed69f3330c9dbe2914bf0bbb7a3"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-automation"
digest = "ab25bf0bd93f88ff58a746c145b080605c01c771f9bf23cafc34aa0aa13199b6"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-ci"
digest = "57fbf695ee16fcb01790b972ac47c87829187645c3d2234d8fff054284cd1854"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]
pages = ["target"]

[[profiles]]
name = "github-watch"
digest = "67ee3e4eff704a12d016dc5dc8a33b97cc5602bc9ecc6195803c6fbb7e407d3e"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-bump"
digest = "6fb25f1839f33bb55c9af579783491de6754aa2eaa7dc3e24f681db88308b1b9"

[profiles.source]
path = "profiles"

[profiles.features]
merge = ["target"]

[[profiles]]
name = "github-dependabot"
digest = "a1fc35307002eb02a1c72040ace02c04293d5c423e252975469e3d097631b5ca"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-labels"
digest = "953cb52fc5bdc3747e4f1e505fc28d3113f4e9a20c7442e1905de3a23a7e30b2"

[profiles.source]
path = "profiles"

[[profiles]]
name = "git-commits"
digest = "6bad256f9243d9481465fc3e41c8892c21e8c528a2beebe9d89f907b9d5c7199"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]

[[profiles]]
name = "git-changelog"
digest = "986e764a2d63288dc0bc380388c536a823031d01fbdc6b5139128124fe1eecca"

[profiles.source]
path = "profiles"

[profiles.features]
breaking-changes = ["target"]

[[profiles]]
name = "spelling"
digest = "e9769c13a761a08e7ae36e29b06fa6bf160cbb357fc2d96c4a995659510faa9b"

[profiles.source]
path = "profiles"

[[profiles]]
name = "toml"
digest = "bc57ff8d34fffc51221daee7de0a576ebff1fb0f72f41dbe703a0c69b0f3297e"

[profiles.source]
path = "profiles"

[profiles.features]
format = ["default"]
lint = ["default"]
schemas = ["devset-collection/schemas"]

[[profiles]]
name = "dprint"
digest = "56bcc783bf88684907113e7576d7d74b11779fe99b440a9bc889bd041a351e8b"

[profiles.source]
path = "profiles"

[[profiles]]
name = "markdown"
digest = "4d56d298f1fbe7e15e869c8ff38bbd2d46089e31aca8c208c6bccc757c719e7f"

[profiles.source]
path = "profiles"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "python"
digest = "16bfac481b4008af1dac2349c60d1bb0c394bbedd254485fafdd2062146a500d"

[profiles.source]
path = "profiles"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "yaml"
digest = "00f89f851f790fbb9ed82d614f4a02a629a3c2a01dc9941676e3454b51091353"

[profiles.source]
path = "profiles"

[profiles.features]
format = ["default"]
lint = ["default"]

[[profiles]]
name = "shell"
digest = "1c5096572121f2c6f701d2447286eed65623592fd977d8670b4f7e684e72c72c"

[profiles.source]
path = "profiles"

[profiles.features]
lint = ["default"]

[[profiles]]
name = "github-workflow-lint"
digest = "94da4e12e4c58fbd1675ad0c26f3057d17e8cc665f04ebb31dd532925c05d244"

[profiles.source]
path = "profiles"

[profiles.features]
actionlint = ["default"]
policies = ["default"]
zizmor = ["default"]

[[profiles]]
name = "suppressions"
digest = "a71c4ff39523cea93a925f230779f6c4b8181472dfff166e5ff46a0b705ddd76"

[profiles.source]
path = "profiles"

[[profiles]]
name = "github-release"
digest = "ba1b094e5b4eb40d9027c4141882773921f9291768c986e1067ec709c9eef544"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]

[[profiles]]
name = "devset"
digest = "3c6950c1ace13cdcff97cb99889fb5a5f720e38c8da010158190ea40552eebdf"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]

[[profiles]]
name = "mdbook-tool"
digest = "cb1f9e1264ba2549d29990d93cab21c61c0bfe371ceb3b963a0416760ecbdc62"

[profiles.source]
path = "profiles"

[[profiles]]
name = "devset-collection"
digest = "84a69d796cf54e20cfaff242cedf165b4eb75f6f96d7816929e0e358e02fe76e"

[profiles.source]
path = "profiles"

[profiles.features]
agents = ["target"]
pins = ["target"]
schemas = ["default"]
site = ["target"]

[[profiles]]
name = "project"
digest = "d42465a0dc157de05a17fb2cb33cab35b1a76678055dff4b5f7290ec0288f025"

[profiles.source]
path = "profiles"

[profiles.features]
conduct = ["target"]
support = ["target"]

[[profiles]]
name = "agents"
digest = "00276ac0a68e4610a78008ee197c604ab1a1e0530ea84d5c71765326564e7ddb"

[profiles.source]
path = "profiles"

[profiles.features]
hook = ["default"]
readability = ["default"]
security = ["default"]

[[profiles]]
name = "vhs"
digest = "21b9f809ca33fbdd8d1cc568f065772512508373c35a8ec0c11491b3097160ed"

[profiles.source]
path = "profiles"

[profiles.features]
merge = ["target"]
